#!/bin/bash
# DNS Setup Instructions - Matrix Platform v11.0.0
# Domain: senorbit.ai
# Server IP: 46.224.42.221

echo "🌍 DNS Setup Instructions for senorbit.ai"
echo ""
echo "⚠️ IMPORTANT: Domain DNS must be configured before deployment!"
echo ""
echo "📋 DNS Records to Add:"
echo ""
echo "Type    Name    Content           TTL     Priority"
echo "--------------------------------------------------------"
echo "A       @       46.224.42.221     Auto    -"
echo "A       www     46.224.42.221     Auto    -"
echo "CNAME   *       46.224.42.221     Auto    -"
echo ""
echo "🔧 How to Setup DNS:"
echo ""
echo "Option 1: Cloudflare"
echo "  1. Add domain to Cloudflare"
echo "  2. Add A record: @ -> 46.224.42.221"
echo "  3. Add A record: www -> 46.224.42.221"
echo "  4. Set SSL/TLS mode to 'Full' or 'Full (strict)'"
echo ""
echo "Option 2: DNS Provider"
echo "  1. Login to your DNS provider"
echo "  2. Add A record: @ -> 46.224.42.221"
echo "  3. Add A record: www -> 46.224.42.221"
echo ""
echo "⏱️ DNS Propagation:"
echo "  - Usually takes 5-30 minutes"
echo "  - Can take up to 48 hours"
echo ""
echo "🔍 Verify DNS:"
echo "  nslookup senorbit.ai"
echo "  dig senorbit.ai"
echo "  host senorbit.ai"
echo ""
echo "✅ After DNS is configured, run deployment script again."

